
coverage:
  range: "70...95" # coverage starts at 70% and is "perfect" at 95%
  status:
    patch:
      default:
        branches: # only perform code coverage on master and dev by default
        - master
        - dev
        target: '80' # the new patch should cover at least 80% to pass
    project:
      default:
        branches: # only perform code coverage on master and dev by default
        - master
        - dev
