
coverage:
  # coverage starts at 70% and is "perfect" at 95%
  range: "70...95"

  status:
    patch:
      default:
        # only perform code coverage on master and dev by default
        branches:
        - master
        - dev

        # the new patch should cover at least 80% to pass
        target: '80' 

    project:
      default:
        # only perform code coverage on master and dev by default
        branches:
        - master
        - dev
